In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(5,name = "a")
b = tf.constant(10, name = "b")

add = tf.add(a,b, name = "sum")

In [3]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter("./graphs", sess.graph)
    print(sess.run(add))
writer.close()

15


In [4]:
c = tf.zeros_like([[2,3],[3,4]], dtype = tf.float32)


In [6]:
with tf.Session() as sess:
    print(sess.run(c).shape)

(2, 2)


In [7]:
d = tf.fill([2,3], value = 1.0)

In [8]:
with tf.Session() as sess:
    print(sess.run(d))

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
q = tf.random_uniform([2,10], 0, 50, dtype = tf.int32)

In [10]:
with tf.Session() as sess:
    print(sess.run(q))

[[ 2 31  1 19 23 10 35 43 10 43]
 [39 27 13 20 11 46  6  2 24 43]]


In [11]:
b = tf.get_variable("Input2", initializer = tf.constant(2))

In [15]:
b = tf.get_variable("matrix", shape=[782,65], initializer = tf.initializers.truncated_normal)

In [8]:
#tf.Variable and tf.get_variable return the same object of class Variable. Both can be treated reversibly.
w1 = tf.get_variable('w1', initializer = tf.constant(2))
w2 = tf.Variable(2, name = "w2")

ValueError: Variable w1 already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "<ipython-input-5-015309f02617>", line 2, in <module>
    w1 = tf.get_variable('w1', initializer = tf.constant(2))
  File "/home/cst/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/home/cst/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):


In [9]:
print(type(w1), type(w2))

<class 'tensorflow.python.ops.variables.Variable'> <class 'tensorflow.python.ops.variables.Variable'>


In [10]:
with tf.Session() as sess :
    sess.run(tf.variables_initializer([w1,w2]))
    print(w1.eval(), type(w1))
    print(w2.eval(), type(w2))

2 <class 'tensorflow.python.ops.variables.Variable'>
2 <class 'tensorflow.python.ops.variables.Variable'>


In [17]:
q = tf.placeholder(tf.float32, shape = [3])
t = tf.constant(4.0)
add1 = tf.add(q,t, name = "addition")


In [19]:
with tf.Session() as sess3:
    writer1 = tf.summary.FileWriter("./graphs/2", sess3.graph)
    print(sess3.run(add1, feed_dict = {q:[1,3,5]}))
writer1.close()

[5. 7. 9.]
